# Generated by Django 2.1.1 on 2018-10-10 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgu', models.IntegerField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Banca',
                'verbose_name_plural': 'Bancas',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('rg', models.CharField(blank=True, max_length=32, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=128, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('bairro', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone_residencial', models.CharField(blank=True, max_length=32, null=True)),
                ('telefone_celular', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_funcional', models.IntegerField(blank=True, max_length=32, null=True)),
                ('professor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplina.Pessoa')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=200, null=True)),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Aluno')),
                ('banca', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Banca')),
                ('orientador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Professor')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.AddField(
            model_name='banca',
            name='professores',
            field=models.ManyToManyField(to='disciplina.Professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Pessoa'),
        ),
    ]
