# Generated by Django 2.1.1 on 2018-10-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0003_auto_20181010_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='banca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Banca'),
        ),
    ]
