# Generated by Django 2.1.1 on 2018-10-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0005_auto_20181017_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientadoracademico',
            name='professor',
        ),
        migrations.AddField(
            model_name='orientadoracademico',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Professor'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='autor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Aluno'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='notaFinal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='periodo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='professoresBanca',
            field=models.ManyToManyField(blank=True, null=True, to='disciplina.Professor'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
