# Generated by Django 2.1.1 on 2018-10-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0006_auto_20181017_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orientadoracademico',
            options={'verbose_name': 'OrientadorAcademico', 'verbose_name_plural': 'OrientadorAcademico'},
        ),
        migrations.AlterField(
            model_name='orientadoracademico',
            name='aluno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disciplina.Aluno'),
        ),
    ]
