# Generated by Django 2.1.1 on 2018-10-25 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0007_auto_20181017_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='autor',
        ),
        migrations.AddField(
            model_name='projeto',
            name='vinculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientador', to='disciplina.OrientadorAcademico'),
        ),
    ]
