# Generated by Django 2.1.1 on 2018-10-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0011_projeto_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.OrientadorAcademico'),
        ),
    ]
