# Generated by Django 2.1.1 on 2018-10-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0012_auto_20181025_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='vinculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='disciplina.OrientadorAcademico'),
        ),
    ]
